name: footrack_front
description: Footrack is an application to help football managers managing their seasons

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # --- State management

  flutter_riverpod: ^2.3.7
  freezed_annotation: ^3.1.0

  # --- Firebase

  #  google_sign_in: ^5.3.2
  firebase_core: ^2.15.1
  firebase_remote_config: ^4.2.7
  firebase_analytics: ^10.5.1
  #  firebase_auth: ^4.1.0
  #  firebase_messaging: ^14.0.3
  cloud_firestore: ^4.9.3
  flamingo: ^3.0.0
  flamingo_annotation: ^1.0.0

  # --- Misc

  intl: ^0.20.2
  wakelock_plus: ^1.2.8
  json_annotation: ^4.8.1
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.1
#  flutter_appcenter_bundle: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # --- API

  build_runner: ^2.4.6
  #  json_serializable: ^6.5.4
  #  retrofit_generator: ^4.0.1
  #  cloud_firestore_odm_generator: ^1.0.0-dev.38
  flamingo_generator: ^1.0.0

  # --- Misc

  #  freezed: ^2.0.3+1
  #  lint: ^1.8.2

flutter:
  uses-material-design: true




